[build]
  publish = "site"
  command = "pip install -r requirements.txt && mkdocs build && cp _redirects site"

# only Python 3.8 is supported at this time:
#  - https://docs.netlify.com/configure-builds/available-software-at-build-time/#languages
[build.environment]
  PYTHON_VERSION = "3.8"
